[package]
name = "The_Missile_Knows_Where_It_Is"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
ggez = "0.9.0"
plotters = "0.3.7"
plotters-bitmap = "0.3.7"
line_drawing = "0.1.0"
rayon = "1.5.3"
